### ISSUE TITLE
slave address should be configurable

### ISSUE THREAD

**Issue by jfburdet** [Efesto/ccs811#1]
Trying to use this lib on https://www.sparkfun.com/products/14348

But the device i2c slave address is 0x5B (instead of hardcoded 0x5A as written in the lib).

Do you have plan to add a configuration parameter ? I tried to refactor the lib, but meta programming parts made it to hard for me.

Any suggestion on how to do that so that I could submit a PR ?

Thanks

**Comment by Efesto** [comment]
addressed in https://github.com/Efesto/ccs811/pull/3
